### ISSUE TITLE
Not showing up as a com port...

### ISSUE THREAD

**Issue by kcorey** [rgujju/paperdink#11]
Hi All,

I've got two computers (a Mac and a PC).
Mac: MacOS 12.4, Arduino IDE 1.8.13
Windows: Latest OS, Arduino 1.8.19, drivers have been installed.

Neither computer sees the paperd being plugged into the USB port, which means that a COM port is never created.

Is there a way to factory reset the paperd, or is this one just bricked?

Could it be unbricked by loading something onto the SD card?

**Comment by rgujju** [comment]
Hello,
The paperd.ink should not get bricked. Have you tried with a different USB cable? Some USB cables don't have the data lines connected which causes such issues.

**Comment by kcorey** [comment]
Thanks very much for writing Rohit!

It was, in fact, the USB cable.  I was surprised because I tried two computers and two USB cables, but apparently both of them were power-only.  They've been disposed of!

I've now got my paperd working from either my Mac or my PC.
