### ISSUE TITLE
Does not open in the latest version of kicad?

### ISSUE THREAD

**Issue by ketan** [rgujju/paperdink#2]
Hi:

Thanks for this great project. I'm attempting to use some aspects of this to build a variometer, by adding an IMU and BMP sensor to this project, and maybe a different paper display and maybe a slightly different form factor.

Could you clarify what version of kicad you're using and where I can grab that version? I'm unable to load this on the latest stable kicad 5.1.5.

**Comment by rgujju** [comment]
Hi Ketan,

You will require the nightly build of kicad to open it.
